{
 "title": "PeerDAS metrics (specs)",
 "description": "Beacon PeerDAS metrics according to the beacon metrics specs",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "network", "label": "Network", "query": { "query": "label_values(network)" } },
   {
    "name": "nodes",
    "label": "Nodes",
    "query": "supernodes : True, full nodes : False"
   },
   { "name": "consensus_client", "label": "Consensus Client", "query": { "query": "label_values(consensus_client)" } },
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  { "title": "PeerDAS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Data column sidecars submitted for gossip processing",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (instance) (increase(beacon_data_column_sidecar_processing_requests_total{network=\"$network\", supernode=~\"$nodes\", consensus_client=~\"$consensus_client\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Data column sidecars verified for gossip",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sum by (instance) (increase(beacon_data_column_sidecar_processing_successes_total{network=\"$network\", supernode=~\"$nodes\", consensus_client=~\"$consensus_client\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Column processing failures",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (instance) (increase(beacon_data_column_sidecar_processing_requests_total{network=\"$network\", supernode=~\"$nodes\", consensus_client=~\"$consensus_client\", instance=~\"$instance\"}[$__interval])) - sum by (instance) (increase(beacon_data_column_sidecar_processing_successes_total{network=\"$network\", supernode=~\"$nodes\", consensus_client=~\"$consensus_client\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Runtime of data column sidecars gossip verification",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(\n  histogram_quantile(0.99, rate(beacon_data_column_sidecar_gossip_verification_seconds_bucket   {network=\"$network\", supernode=~\"$nodes\", consensus_client=~\"$consensus_client\", instance=~\"$instance\"}[$__rate_interval]))\n)\nOR\n(\nhistogram_quantile(0.99, rate(beacon_data_column_sidecar_gossip_verification_milliseconds_bucket{network=\"$network\", supernode=~\"$nodes\", consensus_client=~\"$consensus_client\", instance=~\"$instance\"}[$__rate_interval])) / 1000\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "engine_getBlobsV2 requests",
   "type": "timeseries",
   "description": "Total number of engine_getBlobsV2 requests to an execution layer",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": " (increase(beacon_engine_getBlobsV2_requests_total{network=\"$network\", supernode=~\"$nodes\", consensus_client=~\"$consensus_client\"}[$__interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "engine_getBlobsV2 responses",
   "type": "timeseries",
   "description": "Total number of engine_getBlobsV2 responses to an execution layer",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "targets": [
    {
     "expr": " (increase(beacon_engine_getBlobsV2_responses_total{network=\"$network\", supernode=~\"$nodes\", consensus_client=~\"$consensus_client\"}[$__interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "engine_getBlobsV2 losses",
   "type": "timeseries",
   "description": "Total number of engine_getBlobsV2 losses",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": " (increase(beacon_engine_getBlobsV2_requests_total{network=\"$network\", supernode=~\"$nodes\", consensus_client=~\"$consensus_client\"}[$__rate_interval]))\n -\n (increase(beacon_engine_getBlobsV2_responses_total{network=\"$network\", supernode=~\"$nodes\", consensus_client=~\"$consensus_client\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Runtime of engine_getBlobsV2",
   "type": "timeseries",
   "description": "Full runtime of engine_getBlobsV2",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(\nhistogram_quantile(0.99, rate(beacon_engine_getBlobsV2_runtime_seconds_bucket{network=\"$network\", supernode=~\"$nodes\", consensus_client=~\"$consensus_client\", instance=~\"$instance\"}[$__rate_interval]))\n)\nOR\n(\nhistogram_quantile(0.99, rate(beacon_engine_getBlobsV2_runtime_milliseconds_bucket{network=\"$network\", supernode=~\"$nodes\", consensus_client=~\"$consensus_client\", instance=~\"$instance\"}[$__rate_interval]))  \n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Count of reconstructed columns",
   "type": "timeseries",
   "description": "Total count of reconstructed columns",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (instance) (increase(beacon_data_availability_reconstructed_columns_total{network=\"$network\", supernode=~\"$nodes\", consensus_client=~\"$consensus_client\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time taken to reconstruct columns",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(\nhistogram_quantile(0.99, rate(beacon_data_availability_reconstruction_time_seconds_bucket{network=\"$network\", supernode=~\"$nodes\", consensus_client=~\"$consensus_client\", instance=~\"$instance\"}[$__rate_interval]))\n)\nOR\n(\n  histogram_quantile(0.99, rate(beacon_data_availability_reconstruction_time_milliseconds_bucket{network=\"$network\", supernode=~\"$nodes\", consensus_client=~\"$consensus_client\", instance=~\"$instance\"}[$__rate_interval])) / 1000\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Time taken to compute data column sidecar",
   "type": "timeseries",
   "description": "Time taken to compute data column sidecar, including cells, proofs and inclusion proof",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(\n  histogram_quantile(0.99, rate(beacon_data_column_sidecar_computation_seconds_bucket{network=\"$network\", supernode=~\"$nodes\", consensus_client=~\"$consensus_client\", instance=~\"$instance\"}[$__rate_interval]))\n)\nOR\n(\n  histogram_quantile(0.99, rate(beacon_data_column_sidecar_computation_milliseconds_bucket{network=\"$network\", supernode=~\"$nodes\", consensus_client=~\"$consensus_client\", instance=~\"$instance\"}[$__rate_interval])) / 1000 \n)",
     "legendFormat": "{{instance}}, blob count {{blob_count}}"
    }
   ]
  },
  {
   "title": "Time taken to verify inclusion proof",
   "type": "timeseries",
   "description": "Time taken to verify data column sidecar inclusion proof",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(\n    histogram_quantile(0.99, rate(beacon_data_column_sidecar_inclusion_proof_verification_seconds_bucket{network=\"$network\", supernode=~\"$nodes\", consensus_client=~\"$consensus_client\", instance=~\"$instance\"}[$__rate_interval]))\n)\nOR\n(\nhistogram_quantile(0.99, rate(beacon_data_column_sidecar_inclusion_proof_verification_milliseconds_bucket{network=\"$network\", supernode=~\"$nodes\", consensus_client=~\"$consensus_client\", instance=~\"$instance\"}[$__rate_interval])) / 1000\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Runtime of batched data column kzg verification",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(\nhistogram_quantile(0.99, rate(beacon_kzg_verification_data_column_batch_seconds_bucket{network=\"$network\", supernode=~\"$nodes\", consensus_client=~\"$consensus_client\", instance=~\"$instance\"}[$__rate_interval]))\n)\nOR\n(\nhistogram_quantile(0.99, rate(beacon_kzg_verification_data_column_batch_milliseconds_bucket{network=\"$network\", supernode=~\"$nodes\", consensus_client=~\"$consensus_client\", instance=~\"$instance\"}[$__rate_interval]))  \n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Сustody groups (super nodes)",
   "type": "bargauge",
   "description": "Total number of custody groups for super nodes",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(beacon_custody_groups{network=\"$network\",supernode=\"True\",consensus_client=~\"$consensus_client\", instance=~\"$instance\"})",
     "legendFormat": "{{consensus_client}}-{{execution_client}}"
    }
   ]
  },
  {
   "title": "Custody groups (full nodes)",
   "type": "bargauge",
   "description": "Total number of custody groups for full nodes",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beacon_custody_groups{network=\"$network\", supernode=\"False\", consensus_client=~\"$consensus_client\", instance=~\"$instance\"}",
     "legendFormat": "{{consensus_client}}-{{execution_client}}"
    }
   ]
  },
  {
   "title": "Backfilled custody groups (Super nodes)",
   "type": "bargauge",
   "description": "Total number of custody groups backfilled by a node",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beacon_custody_groups_backfilled{network=\"$network\", supernode=~\"True\", consensus_client=~\"$consensus_client\", instance=~\"$instance\"}",
     "legendFormat": "{{consensus_client}}-{{execution_client}}"
    }
   ]
  },
  {
   "title": "Backfilled custody groups (full nodes)",
   "type": "bargauge",
   "description": "Total number of custody groups backfilled by a node",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beacon_custody_groups_backfilled{network=\"$network\", supernode=~\"False\", consensus_client=~\"$consensus_client\", instance=~\"$instance\"}",
     "legendFormat": "{{consensus_client}}-{{execution_client}}"
    }
   ]
  },
  { "title": "Gossipsub", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Counts sent to each topic",
   "type": "timeseries",
   "description": "Number of gossip messages sent to each topic",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum by (instance) (increase(gossipsub_topic_msg_sent_counts_total{network=\"$network\", supernode=~\"$nodes\", consensus_client=~\"$consensus_client\", instance=~\"$instance\", hash=~\".*/data_column_sidecar.*\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes sent to each topic",
   "type": "timeseries",
   "description": "Number of bytes sent to each topic",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (instance) (increase(gossipsub_topic_msg_sent_bytes_total{network=\"$network\", supernode=~\"$nodes\", consensus_client=~\"$consensus_client\", instance=~\"$instance\", hash=~\".*/data_column_sidecar.*\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Counts received from each topic (with duplicates)",
   "type": "timeseries",
   "description": "Number of gossip messages received from each topic (including duplicates)",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum by (instance, supernode) (increase(gossipsub_topic_msg_recv_counts_unfiltered_total{network=\"$network\", supernode=~\"$nodes\", consensus_client=~\"$consensus_client\", instance=~\"$instance\", hash=~\".*/data_column_sidecar.*\"}[$__interval]))",
     "legendFormat": "{{instance}}, supernode: {{supernode}}"
    }
   ]
  },
  {
   "title": "Counts received from each topic (deduplicated)",
   "type": "timeseries",
   "description": "Number of gossip messages received from each topic (deduplicated)",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 38 },
   "targets": [
    {
     "expr": "sum by (instance, supernode) (increase(gossipsub_topic_msg_recv_counts_total{network=\"$network\", supernode=~\"$nodes\", consensus_client=~\"$consensus_client\", instance=~\"$instance\", hash=~\".*/data_column_sidecar.*\"}[$__interval]))",
     "legendFormat": "{{instance}}, supernode: {{supernode}}"
    }
   ]
  },
  {
   "title": "Counts received from each topic (diff)",
   "type": "timeseries",
   "description": "Difference between number of gossip messages received from each topic including duplicates and deduplicated",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 38 },
   "targets": [
    {
     "expr": "sum by (instance, supernode) (increase(gossipsub_topic_msg_recv_counts_unfiltered_total{network=\"$network\", supernode=~\"$nodes\", consensus_client=~\"$consensus_client\", instance=~\"$instance\", hash=~\".*/data_column_sidecar.*\"}[$__interval])) - sum by (instance, supernode) (increase(gossipsub_topic_msg_recv_counts_total{network=\"$network\", supernode=~\"$nodes\", consensus_client=~\"$consensus_client\", instance=~\"$instance\", hash=~\".*/data_column_sidecar.*\"}[$__interval]))",
     "legendFormat": "{{instance}}, supernode: {{supernode}}"
    }
   ]
  },
  {
   "title": "Bytes received from each topic (with duplicates)",
   "type": "timeseries",
   "description": "Number of bytes received from each topic (including duplicates)",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (instance, supernode) (increase(gossipsub_topic_msg_recv_bytes_unfiltered_total{network=\"$network\", supernode=~\"$nodes\", consensus_client=~\"$consensus_client\", instance=~\"$instance\", hash=~\".*/data_column_sidecar.*\"}[$__interval]))",
     "legendFormat": "{{instance}}, supernode: {{supernode}}"
    }
   ]
  },
  {
   "title": "Bytes received from each topic (deduplicated) ",
   "type": "timeseries",
   "description": "Number of bytes received from each topic (deduplicated) ",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (instance, supernode) (increase(gossipsub_topic_msg_recv_bytes_total{network=\"$network\", supernode=~\"$nodes\", consensus_client=~\"$consensus_client\", instance=~\"$instance\", hash=~\".*/data_column_sidecar.*\"}[$__interval]))",
     "legendFormat": "{{instance}}, supernode: {{supernode}}"
    }
   ]
  },
  {
   "title": "Bytes received from each topic (diff)",
   "type": "timeseries",
   "description": "Number of bytes received from each topic (including duplicates)",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (instance, supernode) (increase(gossipsub_topic_msg_recv_bytes_unfiltered_total{network=\"$network\", supernode=~\"$nodes\", consensus_client=~\"$consensus_client\", instance=~\"$instance\", hash=~\".*/data_column_sidecar.*\"}[$__interval])) - sum by (instance, supernode) (increase(gossipsub_topic_msg_recv_bytes_total{network=\"$network\", supernode=~\"$nodes\", consensus_client=~\"$consensus_client\", instance=~\"$instance\", hash=~\".*/data_column_sidecar.*\"}[$__interval]))",
     "legendFormat": "{{instance}}, supernode: {{supernode}}"
    }
   ]
  },
  { "title": "Req/Resp", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Requests sent",
   "type": "timeseries",
   "description": "Number of requests sent",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (instance) (increase(libp2p_rpc_requests_sent_total{network=\"$network\", supernode=~\"$nodes\", consensus_client=~\"$consensus_client\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests received",
   "type": "timeseries",
   "description": "Number of requests received",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (instance) (increase(libp2p_rpc_requests_received_total{network=\"$network\", supernode=~\"$nodes\", consensus_client=~\"$consensus_client\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of responses sent",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (instance) (increase(libp2p_rpc_responses_sent_total{network=\"$network\", supernode=~\"$nodes\", consensus_client=~\"$consensus_client\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of responses received",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (instance) (increase(libp2p_rpc_responses_received_total{consensus_client=~\"$consensus_client\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests bytes sent",
   "type": "timeseries",
   "description": "Number of requests bytes sent",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (instance) (increase(libp2p_rpc_requests_bytes_sent_total{network=\"$network\", supernode=~\"$nodes\", consensus_client=~\"$consensus_client\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "{{consensus_client}}-{{execution_client}}, {{ip_address}}, {{network}}"
    }
   ]
  },
  {
   "title": "Requests bytes received",
   "type": "timeseries",
   "description": "Number of requests bytes received",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (instance) (increase(libp2p_rpc_requests_bytes_received_total{network=\"$network\", supernode=~\"$nodes\", consensus_client=~\"$consensus_client\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of responses bytes sent",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (instance) (increase(libp2p_rpc_responses_bytes_sent_total{network=\"$network\", supernode=~\"$nodes\", consensus_client=~\"$consensus_client\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of responses bytes received",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (instance) (increase(libp2p_rpc_responses_bytes_received_total{network=\"$network\", supernode=~\"$nodes\", consensus_client=~\"$consensus_client\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}